### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by borgogelli** [F21/jwt#4]
What are the differences between the google-api-php-client encode() method implementation and the Luciferous's one ?
And why do you neeed openssl ? The Hmac algorithm is not enough ?

**Comment by F21** [comment]
The difference between the Google and Luciferous implementation of `encode()` is that the Google one supports the RSA algorithm if I recall correctly.

The reason for Openssl is to support the RSA algorithms like RS256, RS384 and RS512.

This library hasn't been maintained as much as I would like, so I recommend choosing a PHP library from here: https://jwt.io/#libraries-io

Hope that helps! 😄
